creative-darkstar/sparta-games-BE

games/serializers.py, games/views.py
1.Serializers.py의 user 없을 시 로직 수정
2.리뷰 불러오기 시 존재하지 않을 때 처리 로직 추가
3.리뷰 등록한 사람이 더이상 할 수 없게 하는 로직 수정
=> FIX : games

users/urls.py, users/views.py
닉네임 확인 api - url 패턴에 user_pk 들어가있는 부분 수정
유저 데이터 수정 api - game category 수정 시 받은 data에 존재하지 않는 카테고리가 있을 경우 (ex: DB에서 관리하는 카테고리는 fps, rpg 인데 수정 요청으로 넘어온 데이터에 arcade가 있는 경우) bad request 리턴하도록 수정
하나라도 존재하는 카테고리가 있는 경우 그 카테고리로 수정된 채로 정상 반영 (ex: DB에서 관리하는 카테고리는 fps, rpg 이고 수정 요청으로 넘어온 데이터에 arcade, fps인 경우 fps만 반영되어 수정됨)
=> Fix: fixed issue of users app - check nickname, edit user game category

users/views.py
유저 정보 조회 시 게임 카테고리를 pk가 아닌 이름으로 가져오도록 변경
=> Fix: users - get user info - game category name(not pk)

games/views.py
게임 등록 시 index.html에서 canvas.style 값 수정하도록 변경 (고정된 px -> 100%)
=> Edit: games - game_register func

games/urls.py, games/views.py
관리자용 게임 승인용 게임 목록 호출 api 추가
추후 관리자용 기능들 api주소 변경 논의(통보) 예정
api/list -> api/admin/list 이런 식으로
테스트는 완료
최소 is_staff 없으면 동작하지 않도록 만듬
프론트에서 원하는 방향 있으면 추후 수정 예정
=> 관리자 게임 승인필요 게임 목록 호출

accounts/views.py, users/views.py
닉네임 규칙 변경: 기존 4자 이상 30자 이하 영숫자 -> 변경 4자 이상 10자 이하 영숫자
=> Edit: accounts, users - changed nickname validation

games/views.py, users/urls.py, users/views.py
FE 요청으로 games/api/list 에서 게임팩 삭제, users/api/<int:user_pk>/gamepacks/ 로 이관
=> Edit: games, users

games/serializers.py, games/views.py, spartagames/pagination.py
1.리뷰 author,game->author_id, game_id로 변경
2.리뷰 페이지네이션 중 빈값 넣기
3.검색 정렬 제거, keyword 한개로 제목, 카테고리, 메이커이름에 해당하는 게임들로 로직 변경 
4.검색 페이지네이션 리뷰와 같이 씹히는 것 없는 페이지네이션으로 변경
=> Edit:games 리뷰, 검색API 수정

accounts/urls.py, accounts/views.py, users/serializers.py, users/views.py
accounts
- 일반 로그인 및 소셜 로그인 중복가입 블락 처리 완료
- TokenObtainPairView 커스터마이징 하여 일반 로그인 api 신설
- accounts 앱에서 불필요한 라이브러리 삭제, response의 user 데이터 형식 일부 수정 (pk, email, nickname만 담도록)
users
- my games에 register_state 값 추가
=> Edit: accounts - added custom login api view, fixed some logic

accounts/views.py, users/views.py
=> Edit: accounts, users - nickname pattern

accounts/views.py
코드확인을 검증 마지막으로 보냄
->
나머지 검사에서 에러 발생하면 이메일인증을 다시 받아야함. UX으로 편리하도록 변경
=> Edit:accounts 

games/views.py
1.실패, 에러 응답에 에러코드 추가
2.즐겨찾기  IsAuthenticated 장고 응답을 커스텀화 완료
3.messeage->message(오타 수정)
- 추가로 생각 해볼 것 IsAuthenticated 관련 전역적 커스텀 응답을 생각해보기가 필요한 듯 합니다.
=> Edit:games 실패 응답에 에러코드 추가, 즐겨찾기 장고응답을 커스텀화 하기

accounts/views.py
에러 코드 추가
message["id"] 의 큰 따옴표를 작은 따옴표로 수정
=> Edit: accounts - add error code

accounts/views.py, users/views.py
닉네임: 한영숫자 4자 이상 12자 이하
비밀번호: 영, 숫자, 특수문자 각각 최소 1개 이상으로 이루어진 8자 이상 32자 이하
특수문자 목록: ~`!@#$%^&*()_-+={}[]|:;"'<>,.?/
로직 수정이 단순하여 별도 코드 리뷰를 가지지 않는 핫픽스
=> Edit: accounts, users - changed nickname and password regex pattern

accounts/views.py, games/views.py, users/views.py
닉네임: 한영숫자 4자 이상 12자 이하
비밀번호: 영, 숫자, 특수문자 각각 최소 1개 이상으로 이루어진 8자 이상 32자 이하
특수문자 목록: ~`!@#$%^&*()_-+={}[]|:;"'<>,.?/
로직 수정이 단순하여 별도 코드 리뷰를 가지지 않는 핫픽스
=> 2025-05-23 핫픽스 건(닉네임, 비밀번호 정규식 수정)

games/views.py
`games/api/list` 최근 업데이트된 게임 추가
기존 로직을 그대로 사용하고 있어, 별도 리뷰 없이 풀 리퀘 적용
=> Edit: games - added updated games

commons/views.py, teambuildings/pagination.py, teambuildings/serializers.py, teambuildings/urls.py, teambuildings/views.py, users/urls.py, users/views.py
팀빌딩 포스트 검색
팀빌딩 프로필 검색
팀빌딩 댓글 CRUD
팀빌딩 관련 select option 값들 리스트 반환 api (`teams/api/purpose-list/`, `teams/api/duration-list/`, `teams/api/meeting-type-list/`, `teams/api/role-list/`)
=> Add: 팀빌딩 포스트 검색, 팀빌딩 프로필 검색, 팀빌딩 댓글 CRUD

teambuildings/views.py
- import 부 정리
- 코드 라인 정리
- s3 에 요청 보낼 때, 오브젝트 키 리스트가 비어있는 경우 고려 (비어있을 경우 요청을 보내지 않도록)
=> 20250705 수정 사항

teambuildings/serializers.py, teambuildings/views.py
팀빌딩 추천글 목록 로직 수정
- 마감되지 않은 글들을 불러오도록 수정
- 로그인 유저의 프로필 기반 맞춤 팀빌딩 모집글을 1순위, 마감 임박 팀빌딩 모집글을 2순위로 함
- 1순위 글 개수가 4개 미만일 경우, 1순위 글과 중복되지 않은 2순위 글로 부족한 개수를 채움
=> 250708 변경사항 배포에 반영

teambuildings/views.py
team_build_posts -> teambuild_posts 로 변경
=> Edit: change response of TeamBuildPostAPIView - GET request

games/utils.py, games/views.py, spartagames/custom_middleware.py, spartagames/exceptions.py, spartagames/settings.py
- 커스텀 미들웨어 및 에러 핸들러 추가 (permission_classes = [IsAuthenticated] 등 django 에서 기본으로 제공하는 응답 및 예외에 대해서도 std_response 가 적용되도록 함)
- 게임 업로드 시 디스코드 알림 추가
=> 20250725 작업 1

commons/consumers.py, commons/serializers.py, qnas/views.py, spartagames/asgi.py
1. FE 와 테스트 후 수정 필요 코드 반영
- asgi 세팅 일부 변경
- consumers.py 에서 웹소켓 생성 및 연결 시 로직 수정
2. FE 요청사항 반영
- 검수 승인 및 반려 시 user 값을 제작자 정보로 하도록 수정
- NotificationSerializer의 noti_type 을 label 값으로 하도록 수정
- NotificationSerializer 에 content_id 포함
=> 알람 기능 수정 사항 반영
